### ISSUE TITLE
Cannot start service blog_nginx

### ISSUE THREAD

**Issue by asopiah** [CharbelJ/blog#2]
```
ERROR: for blog_nginx  Cannot start service blog_nginx: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"entrypoint.sh\": executable file not found in $PATH": unknown
ERROR: Encountered errors while bringing up the project.

```
Please assist to fix the above error

**Comment by asopiah** [comment]
> ```
> ERROR: for blog_nginx  Cannot start service blog_nginx: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"entrypoint.sh\": executable file not found in $PATH": unknown
> ERROR: Encountered errors while bringing up the project.
> ```
> 
> Please assist to fix the above error

Ignore the above.

**Comment by nageebt** [comment]
> > ```
> > ERROR: for blog_nginx  Cannot start service blog_nginx: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"entrypoint.sh\": executable file not found in $PATH": unknown
> > ERROR: Encountered errors while bringing up the project.
> > ```
> > 
> > 
> > Please assist to fix the above error
> 
> Ignore the above.

Would love to know what you did to resolve this.

**Comment by asopiah** [comment]
> > > ```
> > > ERROR: for blog_nginx  Cannot start service blog_nginx: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"entrypoint.sh\": executable file not found in $PATH": unknown
> > > ERROR: Encountered errors while bringing up the project.
> > > ```
> > > 
> > > 
> > > Please assist to fix the above error
> > 
> > 
> > Ignore the above.
> 
> Would love to know what you did to resolve this.

You can solve the issue by making the **entrypoint.sh** executable by simply running below command
`chmod +x docker-nginx/entrypoint.sh`

**Comment by nageebt** [comment]
Be sure to `chmod +x docker-nginx/entrypoint.sh `  It resolved this issue for me.

> > > ```
> > > ERROR: for blog_nginx  Cannot start service blog_nginx: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"entrypoint.sh\": executable file not found in $PATH": unknown
> > > ERROR: Encountered errors while bringing up the project.
> > > ```
> > >

**Comment by CharbelJ** [comment]
I have just updated the Dockerfile in docker-nginx
